global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.

# tag::adocPrometheus[]
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['172.17.0.1:9090']
  - job_name: 'fights'
    static_configs:
      - targets: ['172.17.0.1:8082']
  - job_name: 'heroes'
    static_configs:
      - targets: ['172.17.0.1:8083']
  - job_name: 'villains'
    static_configs:
      - targets: ['172.17.0.1:8084']
# end::adocPrometheus[]
